#!/usr/bin/env bash

root=$(git rev-parse --show-toplevel)
source $root/scripts/common.bash
files=$(git status --porcelain | grep -v -E "^\sD\s" | awk '{ $1=""; print}' | grep -E *.go$)
if [[ -z $files ]]; then
    exit 0
fi

set -e

for file in "$files"; do
    file=${file#' '}
    filesAbsPath="$root/${file} $filesAbsPath"
done

filesAbsPath=${filesAbsPath%' '}
golint --set_exit_status "$filesAbsPath"
go vet "$filesAbsPath"
unformattedFiles=$(gofmt -l "$filesAbsPath")
_set_fmt_error_code() {
    if [[ -n $unformattedFiles ]]; then
        echo -e "${yellow_bg}${black_txt}${bold}The following files are not properly formatted."
        echo -e "Run 'go fmt'${reset}"
        return 1
    fi
}
_set_fmt_error_code

set +e
